name: Build and publish npm package

on:
  release:
    types: [created]

jobs:
  call-publisher:
    uses: fragnarok/Custom-GitHub-Action-Scripts/.github/workflows/build-test-publish-npm.yml@main
    secrets: inherit
